---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master
  namespace: {{NS}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: {{NS}}
      type: jenkins-master
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-master
  namespace: {{NS}}
  labels:
    name: jenkins
    role: master
spec:
  replicas: 1
  selector:
    name: jenkins
    role: master
  template:
    metadata:
      name: jenkins-master
      labels:
        name: jenkins
        role: master
    spec:
      containers:
      - name: jenkins-master
        image: quay.io/jcmoraisjr/jenkins-master:1.651.3
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Sao_Paulo
        volumeMounts:
        - name: jenkins
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: jenkins-master
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-master
  namespace: {{NS}}
  labels:
    name: jenkins
    role: master
  annotations:
    serviceloadbalancer/lb.host: "{{DOM}}"
    serviceloadbalancer/lb.sslTerm: "true"
spec:
  ports:
  - targetPort: 8080
    port: 80
  selector:
    name: jenkins
    role: master
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-discovery
  namespace: {{NS}}
  labels:
    name: jenkins
    role: master
spec:
  ports:
  - port: 50000
  selector:
    name: jenkins
    role: master
