---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-agent
  namespace: {{NS}}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: {{NS}}
      type: jenkins-agent
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-agent
  namespace: {{NS}}
  labels:
    name: jenkins
    role: agent
spec:
  replicas: 1
  selector:
    name: jenkins
    role: agent
  template:
    metadata:
      name: jenkins-agent
      labels:
        name: jenkins
        role: agent
    spec:
      containers:
      - name: jenkins-agent
        image: quay.io/jcmoraisjr/jenkins-agent:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Sao_Paulo
        - name: MASTER_HOST
          value: jenkins-master
        - name: DISCOVERY_HOST
          value: jenkins-discovery
        - name: rootfs
          value: /var/jenkins
        volumeMounts:
        - name: jenkins
          mountPath: /var/jenkins
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: jenkins-agent
