apiVersion: v1
kind: Secret
metadata:
  name: lb-crt
  namespace: kube-system
type: Opaque
data:
  cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lKQU9RUithRmp3L2xJTUEwR0NTcUdTSWIz
    RFFFQkJRVUFNQlF4RWpBUUJnTlYKQkFNVENXeHZZMkZzYUc5emREQWVGdzB4TmpBM01qUXlNREV5TVRWYUZ3MHlOakEzTWpR
    eU1ERXlNVFZhTUJReApFakFRQmdOVkJBTVRDV3h2WTJGc2FHOXpkRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFE
    Q0NBUW9DCmdnRUJBTmpjcklWbEFLU0pvMVNkZVo3TGdzcGprSWpnMEtNNVRrMHZsWGwxMnBZcWNyRHYyeklBZGJReXJNZE8K
    NC9CRlk2MUEzdGMzd1REOWhQTVJJYlVZSjVGRndXc0loa0dKR2ZSdGxHTkkvdUxUWi8wRFY0TU1lVGJLUFFUWQpidUlSNUJD
    RWlZNzY0b1NOWE5FS1dtbVJpYjBhSlA3YUtZOXZIc3ViS3JxbmRSbnE5alBYVmFvNkNickU1elJWCnJmVXl0TnJaaVJ2S0Jp
    WVU0WkZ6eFJxaWprVUd0aDJFdFp0Tk9HaW5xVTE1RjBGcC9PU1M1RlRpbnk1bGI5eXgKTlNjenBRd292VFZpcFl4c3pPbjNu
    Q3o2VndNTko3RVltdkhrNUJtRG9RbzBmdDIycTlHUHovWDQ2Z3g1UTdicwpiSDc2bGlnVlVKakpjMW9pai9ZU1JGYmxnc0VD
    QXdFQUFhTjFNSE13SFFZRFZSME9CQllFRlBPK1VCSGxVS1loCjdNMjJLT3plSklFVDFESHVNRVFHQTFVZEl3UTlNRHVBRlBP
    K1VCSGxVS1loN00yMktPemVKSUVUMURIdW9SaWsKRmpBVU1SSXdFQVlEVlFRREV3bHNiMk5oYkdodmMzU0NDUURrRWZtaFk4
    UDVTREFNQmdOVkhSTUVCVEFEQVFILwpNQTBHQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUJRbGU3czdJb1BnSUVna2hkUExiTVQy
    TCtHYkYycFd6V1VRd29hCi9oNUNIbmdkdzQ0bDUybndmR2FUOUlKdXp5QXdHSktIN2FJYTJvb1FvRGFqSDhRdVNNaTVFdDha
    VXdjK1VhZVgKZmhKa2xCT0ZmL2VSU2pOdi9kWXhKbUVVQXk3RG8rZEp0MlhadXk1aG9VSGFhU0d1cGNLZEhaTmt2N0J6MGc2
    eQowbUZROTdlWFpsdnF6OUEvR0xhNHZvWXZFdXBsTmRsV09jdlJXWk1ZVEdOQXhMZ2xTUGpEYi91MWFVbXI5QTZhCjcrQjgx
    SWRPSjM5WlhDODBrMjVMdUdLT2dJUnR2cnk2UFZDQ1Vja21hV3E2RC9hMVpZeWdhamFYUHBzSXRFUDIKcUp4OEpGam5neFEr
    b0dIVHJ1TmdhT1BQY253UkgyR1VZMnRUWXRZODFVNi9rWmZvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJ
    TiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMk55c2hXVUFwSW1qVkoxNW5zdUN5bU9RaU9EUW96bE9U
    UytWZVhYYWxpcHlzTy9iCk1nQjF0REtzeDA3ajhFVmpyVURlMXpmQk1QMkU4eEVodFJnbmtVWEJhd2lHUVlrWjlHMlVZMGor
    NHRObi9RTlgKZ3d4NU5zbzlCTmh1NGhIa0VJU0pqdnJpaEkxYzBRcGFhWkdKdlJvay90b3BqMjhleTVzcXVxZDFHZXIyTTlk
    Vgpxam9KdXNUbk5GV3Q5VEswMnRtSkc4b0dKaFRoa1hQRkdxS09SUWEySFlTMW0wMDRhS2VwVFhrWFFXbjg1SkxrClZPS2ZM
    bVZ2M0xFMUp6T2xEQ2k5TldLbGpHek02ZmVjTFBwWEF3MG5zUmlhOGVUa0dZT2hDalIrM2JhcjBZL1AKOWZqcURIbER0dXhz
    ZnZxV0tCVlFtTWx6V2lLUDloSkVWdVdDd1FJREFRQUJBb0lCQUE1Njdhb2FqR2h3S0UvRwpGQkRlVmVWZHNKRHpNZnMwSUY1
    WEJ3d05Lb05NWWt3ZU4reW15elUxRFFSaDZDWnErN1RkMkFOVzNiZC90aGprCjAvTmJvWWk1dDZpRjhURC9EcFNibklUa291
    QlNiV2NmaWdCZUhObmp0eDlUdEZPMERoNXNPeU1vN1djY2FVNHIKK3MyQndraTJMakkyTHdBODB6bVZLczA3MFQzaHF3WkM1
    c3VrT214VjZYSzQwYVlRclZRcU5FaXpnY0IweHFJVgpUZGVHYlBVSXh2cVNtdkx4YXZ0U00wak1jRnNCSzlVRkZSQzBsWnNX
    MVlTa0VpYk5aNVFwV3FIYTVvRXFDVUlyCjc0S2QyZFV6dWZ1Tm01azZiU0RvWHdtUEtHTWVnSHQyc2JIRGxpdWpDQ240NzFI
    Q3lwYWpTWUltenkrMVhQNHEKSnBhL0FJRUNnWUVBNy9hWjRGbGdQRnMvNlVCbjR4UTJXVEJlWDBZd3Q3QjViQjUxUWc0RWQz
    c0QydnFCMnlIcgppYWsvNHZaSUtYYkFoYlh1VGtZS3FyRm1ISU1DU29sODh2d1hrRCsxSWZyQndMNEYyY1Y2NlVXZ2E1MjIw
    ak90CmhNWXBZK1c2ajBsT093RW5VMXRaS09Xa3Rtb1JtbEFhbnNMY2RUVnNncTlGbHoybUNNaGcvelVDZ1lFQTUxclkKaW5Z
    ZFR2cHBDbzFOZW5KbVphM0kwNDBSNkt1RHBNamdrRmJIOG96VnNVbkRXWEtTOGQwTi83cmtrMyt4QlkvdgpXR2tTamdPR0Uz
    OS90K2MzZmdXM1k0ZGZWZTg4N0pHcWhoMjAvVDFWWWNyZFkwRG42RUcyNkZINmhpVVdWQ2FSCjFtOUNLQ2loeU9tU3JCM25N
    emQ3VGpNanc5TlFTMW52ZHZEd3F0MENnWUVBaWYyZVdVUXNNaWtySkgvei9jSm0KeW4wbEY5YXVOME9WWDVaWVNjYnp6SjJD
    QncvZFV0MDdyR3NXb1BhTllzSzJUVzNrZjBDSjY4U2QrckZmeE9zeApYaTJYZzAwUFpWM2t3MmpDeG90b2RmS2pJSitPUFd5
    WVVPei9ha0gyT1dXblJna1F5eitSa3hJVDJRNC8xeVJQCldwS2w0Z1Q1eEdEMFBOZW52Zzgwc0MwQ2dZQlRGc1JvVGUxT3ZR
    NVdsTkw3by9SMGxncG5OK1h6cXcyWGMvRjYKeFVBQU0yWlh5c2NXNjlnc2R4aWMvSkUxREFvV2xrLytiNVlUWE42ZFNCQWxp
    eXZaM2RHME5CMGdMdEN4b2NzZAphYlBqczFCajA4alk2YW1nTjJHcVpDN1dXS0dCVFd6WkY1SXAvQlhHbzJSaTNrWjNsWGg2
    YUZGeTlnU0RXMlJ1ClVqQU5IUUtCZ0YxNUk5WkEwZGMvMDFldTFnZDVZc1Z6OGhRSFZWM3FIUmhrUWp6N0ZiY0w0RE9SQUhB
    eTJMZ1AKdkt0TUt3U1NyMnVPckgwOUxIbEEyOE4vR2F6V3hzZXdndmcrVWcrZG9MdFB5Rkw1T285WXNJa1pkcitjdlNmeApG
    bmhFQ3NFM05MUzNFNUpmY1VvZnBlY3RhaFlNVmpDVStHLzk5dVpxc3ZXbHhCSmtsa2pzCi0tLS0tRU5EIFJTQSBQUklWQVRF
    IEtFWS0tLS0tCg==
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: lb
  namespace: kube-system
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      hostNetwork: true
      nodeSelector:
        role: loadbalancer
      containers:
      - name: haproxy
        image: quay.io/jcmoraisjr/kube-loadbalancer
        args:
        - --ssl-cert=/var/ssl/cert
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: lb-ssl
          mountPath: /var/ssl
      volumes:
      - name: lb-ssl
        secret:
          secretName: lb-crt
